"""
04_fuzzy_match_post10cou.py
===========================
TF-IDF Fuzzy Name Matching — Final Cross-Country Pass (Post-10-Country Stage)

PURPOSE
-------
Runs a final fuzzy name-matching pass on all exporter firm names that were
NOT matched in any of the 10 country-level passes (script 03). At this stage,
the query set is small enough that a single cross-country match is both fast
and necessary to catch firms that operate across multiple countries or whose
names differ from their country-specific Orbis/DNB entry.

This is Stage 3 of the matching pipeline described in 02_match_customs_mne.do.

METHOD
------
Identical to script 03:
  1. TF-IDF character n-gram vectorisation of the Orbis/DNB reference corpus.
  2. NMSLIB approximate nearest-neighbour search (k=2).
  3. Export match pairs and similarity scores for AI review.

INPUTS  (relative to project root / data/intermediate/)
--------
  Merge_DNB_Orbis_for_fuzzy_post10cou.csv     — Orbis/DNB unmatched firm names
  list_exporters_10c_ALC_for_fuzzy_post10cou.csv — customs unmatched firm names
  (Both files are generated by 02_match_customs_mne.do, Stage 2c)

OUTPUTS (relative to project root / data/intermediate/)
---------
  fuzzy_match_post10cou.csv   — match pairs with similarity score (conf)

DEPENDENCIES
------------
  See requirements.txt. Key packages: scikit-learn, nmslib, ftfy, pandas.

NOTE ON SIMILARITY SCORE
------------------------
  Same scoring convention as script 03.
  conf > -0.6 is filtered in 01_match_customs_mne.do before AI review.

AUTHORS
-------
  Sebastian Velasquez (IDB)
  Approach based on sparse TF-IDF fuzzy matching (Tate, 2021).

LAST UPDATED: March 2026
"""

import re
import time
from pathlib import Path

import numpy as np
import pandas as pd
import nmslib
from ftfy import fix_text
from sklearn.feature_extraction.text import TfidfVectorizer

# ---------------------------------------------------------------------------
# PATH CONFIGURATION
# All paths are derived from the project root automatically.
# ---------------------------------------------------------------------------

project_root = Path(__file__).resolve().parent.parent
data_int     = project_root / "data" / "intermediate"


# ---------------------------------------------------------------------------
# TEXT NORMALISATION
# ---------------------------------------------------------------------------

def ngrams(string: str, n: int = 3) -> list:
    """
    Convert a company name string into character n-grams for TF-IDF.

    Normalisation steps:
      1. Lowercase
      2. Fix unicode/encoding artefacts (ftfy)
      3. Remove 'trading as' prefixes
      4. Strip non-ASCII characters
      5. Remove common punctuation  )( . | [ ] { } ' -
      6. Title-case normalisation
      7. Collapse multiple spaces
      8. Pad with leading/trailing spaces for edge n-grams
    """
    string = str(string).lower()
    string = fix_text(string)
    string = string.split("t/a")[0]
    string = string.split("trading as")[0]
    string = string.encode("ascii", errors="ignore").decode()

    chars_to_remove = list(r")(.|[]{}'-")
    rx = "[" + re.escape("".join(chars_to_remove)) + "]"
    string = re.sub(rx, "", string)
    string = string.title()
    string = re.sub(r" +", " ", string).strip()
    string = " " + string + " "

    return ["".join(ngram) for ngram in zip(*[string[i:] for i in range(n)])]


# ---------------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    ref_csv   = data_int / "Merge_DNB_Orbis_for_fuzzy_post10cou.csv"
    query_csv = data_int / "list_exporters_10c_ALC_for_fuzzy_post10cou.csv"
    out_csv   = data_int / "fuzzy_match_post10cou.csv"

    print(f"Project root : {project_root}")
    print(f"Reference    : {ref_csv.name}")
    print(f"Query        : {query_csv.name}")
    print(f"Output       : {out_csv.name}")

    # --- Build TF-IDF matrix from Orbis/DNB reference names ---
    t0        = time.time()
    df_ref    = pd.read_csv(ref_csv, encoding="latin1")
    ref_names = list(df_ref["company_name"].unique().astype("U"))

    vectorizer    = TfidfVectorizer(min_df=1, analyzer=ngrams)
    tf_idf_matrix = vectorizer.fit_transform(ref_names)
    print(f"\nTF-IDF matrix: {tf_idf_matrix.shape}  ({time.time()-t0:.1f}s)")

    # --- Vectorise query (unmatched customs firms) ---
    df_query     = pd.read_csv(query_csv, encoding="latin1")
    query_names  = list(df_query["firm_name"].unique().astype("U"))
    query_matrix = vectorizer.transform(query_names)

    # --- Build NMSLIB inverted index ---
    index = nmslib.init(
        method="simple_invindx",
        space="negdotprod_sparse_fast",
        data_type=nmslib.DataType.SPARSE_VECTOR,
    )
    index.addDataPointBatch(tf_idf_matrix)

    t1 = time.time()
    index.createIndex()
    print(f"NMSLIB index built ({time.time()-t1:.1f}s)")

    # --- Query: k=2 nearest neighbours per firm name ---
    K           = 2
    num_threads = 4

    t2        = time.time()
    nbrs      = index.knnQueryBatch(query_matrix, k=K, num_threads=num_threads)
    n_queries = query_matrix.shape[0]
    elapsed   = time.time() - t2
    print(
        f"kNN query: {elapsed:.1f}s total  "
        f"({elapsed/n_queries:.4f}s per query)"
    )

    # --- Collect and export results ---
    rows = []
    for i, query_name in enumerate(query_names):
        try:
            matched_name = ref_names[nbrs[i][0][0]]
            conf         = nbrs[i][1][0]
        except (IndexError, TypeError):
            matched_name = "no match found"
            conf         = None
        rows.append([query_name, matched_name, conf])

    matches = pd.DataFrame(rows, columns=["original_name", "matched_name", "conf"])
    results = df_query.merge(matches, left_on="firm_name", right_on="original_name")
    results.to_csv(out_csv, index=False)
    print(f"\nSaved {len(results):,} rows -> {out_csv}")
    print("\nNext: run AI review on data/intermediate/ia_review/final_match_preIA.csv")
    print("      (see AI prompt in 02_match_customs_mne.do, Stage 3)")
